#ifndef INKFUSE_COMPILATIONCONTEXT_H
#define INKFUSE_COMPILATIONCONTEXT_H

#include "codegen/IR.h"
#include "codegen/Value.h"
#include "algebra/Pipeline.h"

namespace inkfuse {

    struct Suboperator;
    struct PipelineDag;

    /// Context for compiling a pipeline.
    struct CompilationContext {

        /// Central program being generated by this compilation context.
        IR::Program program;

        /// The PipelineDAG being wrapped by this CompilationContext.
        PipelineDagPtr pipeline_dag;

        /// Get the next pipeline to execute.
        Pipeline& getNextPipeline();

        /// Get the operator offset within the global state.
        IR::UI4 getOperatorOffset(Suboperator& op);

        /// Generate code for the backing pipeline.
        IR::Program generateCode(Pipeline& pipe);

    };

}

#endif //INKFUSE_COMPILATIONCONTEXT_H
