name: BuildAndTest

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-22.04
    # Run builds and tests both in Debug and RelWithDebInfo
    strategy:
        matrix:
            build-type: [Debug, RelWithDebInfo]
    steps:
    - uses: actions/checkout@v2
    - name: Build
      uses: ./.github/actions/build
      with:
          build-type: ${{ matrix.build-type }}
    - name: Test
      working-directory: ${{github.workspace}}/build
      # Unfortunately we're running into https://github.com/llvm/llvm-project/issues/59432
      # This is some Ubuntu packaging issue that causes alloc/dealloc mismatches when asan
      # is enabled with libc++
      run: ASAN_OPTIONS=detect_odr_violation=0,alloc_dealloc_mismatch=1 ./tester
      
